# Development Docker Compose Configuration
# Use this for local development with hot reload

version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: toala_mongodb_dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: toala_development
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - toala_dev_network

  # Backend API (Development)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: toala_backend_dev
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=toala_development
      - JWT_SECRET=dev_jwt_secret_not_for_production
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_HOURS=24
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    networks:
      - toala_dev_network
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  # Frontend Application (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: toala_frontend_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - toala_dev_network

volumes:
  mongodb_dev_data:
    driver: local

networks:
  toala_dev_network:
    driver: bridge
